//= require_self
//= require jquery-1.10.2
//= require vendor/bootstrap/js/bootstrap
//= require json2
//= require lodash
//= require backbone
//= require backbone-validation
//= require handlebars-v1.2.0
//= require namespace
//= require routing
//= require router
//= require_tree ./models
//= require_tree ./templates
//= require_tree ./views
//= require_tree ./collections
//= require app
